CREATE TABLE cafes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    short_description VARCHAR(500) NOT NULL,
    address VARCHAR(255) NOT NULL,
    road_address VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    phone VARCHAR(50),
    opening_hours VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    activated_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cafe_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    description VARCHAR(500) NOT NULL,
    image_original_url VARCHAR(1000) NOT NULL,
    image_thumbnail_url VARCHAR(1000) NOT NULL,
    image_blurhash VARCHAR(255),
    representative BOOLEAN NOT NULL,
    released_at DATE,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE cafe_metrics (
    cafe_id BIGINT PRIMARY KEY,
    view_count_daily BIGINT NOT NULL,
    view_count_weekly BIGINT NOT NULL,
    view_count_total BIGINT NOT NULL,
    rating_average NUMERIC(4, 2) NOT NULL,
    rating_count BIGINT NOT NULL,
    rating_score NUMERIC(8, 3) NOT NULL,
    last_viewed_at TIMESTAMP,
    hot_score NUMERIC(10, 3) NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_cafe_status_lat_lng ON cafes (status, latitude, longitude);
CREATE INDEX idx_menu_cafe_representative ON menu_items (cafe_id, representative, status);
CREATE INDEX idx_metric_hot_score ON cafe_metrics (hot_score DESC);
CREATE INDEX idx_metric_rating_score ON cafe_metrics (rating_score DESC);
