spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3307/cafe_map_lab?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
    username: ${DATABASE_USERNAME:cafe_lab}
    password: ${DATABASE_PASSWORD:cafe_lab}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    locations: classpath:db/migration/mysql
